apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-gateway
  labels:
    app: agent-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agent-gateway
  template:
    metadata:
      labels:
        app: agent-gateway
    spec:
      containers:
        - name: app
          image: <ACR_NAME>.azurecr.io/agent-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: JWKS_URI
              value: "https://login.yourdomain.com/realms/demo/protocol/openid-connect/certs"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: agent-gateway
  labels:
    app: agent-gateway
spec:
  type: ClusterIP
  selector:
    app: agent-gateway
  ports:
    - name: http
      port: 8080
      targetPort: 8080 