apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detection-agent
  labels:
    app: fraud-detection-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-detection-agent
  template:
    metadata:
      labels:
        app: fraud-detection-agent
    spec:
      containers:
        - name: app
          image: <ACR_NAME>.azurecr.io/fraud-detection-agent:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 20
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: fraud-detection-agent
  labels:
    app: fraud-detection-agent
spec:
  type: ClusterIP
  selector:
    app: fraud-detection-agent
  ports:
    - name: http
      port: 8083
      targetPort: 8083 